mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: ''
  database: <%= "forplay_#{Rails.env}" %>

defaults: &defaults
  pool: 5
  timeout: 5000
  host: <%= ENV['DB_HOST'] || "localhost" %>
  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
