development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: ''
  database: <%= "forplay_#{Rails.env}" %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: ''
  database: <%= "forplay_#{Rails.env}" %>
  host: localhost

staging:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: admin
  password: password
  database: forplay_production
  host: forplay.ci3jtk7usdj0.eu-west-2.rds.amazonaws.com
  port: 3306
