development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: ''
  database: <%= "forplay_#{Rails.env}" %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: ''
  database: <%= "forplay_#{Rails.env}" %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: ''
  database: <%= "forplay_#{Rails.env}" %>
  host: localhost
